name: CI

on: [push, pull_request]

jobs:
  build_windows:
    name: Build Test Client for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Configure and Build
        run: |
          mkdir -p test/build && cd test/build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
          cp Release/odin_minimal.exe .
      - name: Upload Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: odin-minimal-windows-x86_64
          path: |
            test/build/odin_minimal.exe
            test/build/odin.dll

  build_linux:
    name: Build Test Client for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Configure and Build
        run: |
          mkdir -p test/build && cd test/build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          patchelf --set-rpath '$ORIGIN' ./odin_minimal
      - name: Upload Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: odin-minimal-linux-x86_64
          path: |
            test/build/odin_minimal
            test/build/libodin.so

  build_macos:
    name: Build Test Client for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Configure and Build
        run: |
          mkdir -p test/build && cd test/build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
      - name: Upload Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: odin-minimal-macos-x86_64
          path: |
            test/build/odin_minimal
            test/build/libodin.dylib
